// Auto-generated by @idiomi/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomiProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idiomi/react';
import {
  createLocaleHead,
  createLocaleLoader,
  createUrlRewriter,
} from '@idiomi/tanstack-react';
import {
  defaultLocale,
  detection,
  locales,
  prefixStrategy,
} from './.generated/config';
import { reverseRoutes, routePatterns, routes } from './.generated/routes';
import type { IdiomiTypes, Locale } from './.generated/types';

export const LocaleHead = createLocaleHead({
  metadataBase: 'http://localhost:5177',
  locales: ['en', 'es'],
  defaultLocale: 'en',
  routes,
  reverseRoutes,
  prefixStrategy: 'as-needed',
});

export const { localeLoader, detectClientLocale } = createLocaleLoader<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  detection,
});

export const { deLocalizeUrl, localizeUrl } = createUrlRewriter<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  routes,
  reverseRoutes,
  routePatterns,
});

export { getLocaleHead } from '@idiomi/react';

export const Trans = createTrans<IdiomiTypes>();

export const useT = createUseT<IdiomiTypes>();

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();

export type { IdiomiTypes, Locale };
