// Auto-generated by @idiomi/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomiProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idiomi/react';
import { createLocaleHead, createUrlRewriter } from '@idiomi/tanstack-react';
import {
  createHandleLocale,
  createLocaleLoader,
} from '@idiomi/tanstack-react/start';
import {
  defaultLocale,
  detection,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import { reverseRoutes, routePatterns, routes } from './.generated/routes';
import type { IdiomiTypes, Locale } from './.generated/types';

export { locales, defaultLocale } from './.generated/config';

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  routes,
  reverseRoutes,
  prefixStrategy,
});

export const handleLocale = createHandleLocale<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  detection,
});

export const { detectClientLocale } = createLocaleLoader<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  detection,
});

export const { deLocalizeUrl, localizeUrl } = createUrlRewriter<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  routes,
  reverseRoutes,
  routePatterns,
});

export { getLocaleHead } from '@idiomi/react';

export const Trans = createTrans<IdiomiTypes>();

export const useT = createUseT<IdiomiTypes>();

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();

export type { IdiomiTypes, Locale };
