// Auto-generated by @idioma/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomaProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idioma/react';
import type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
} from './.generated/types';

export const Trans = createTrans<TranslationKey, MessageValues, MessageComponents>();
export const useT = createUseT<StringOnlyKey, MessageValues>();
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
};
