// Auto-generated by @idioma/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomaProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idioma/react';
import type { IdiomaTypes, Locale } from './.generated/types';

export const Trans = createTrans<IdiomaTypes>();
export const useT = createUseT<IdiomaTypes>();
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type { IdiomaTypes, Locale };
