// Auto-generated by @idiomi/core
// Do not edit directly
// Client components (Trans, useT, Link, LocaleHead) are in client.ts
// Import from './client' for client-side components

export { locales, defaultLocale } from './.generated/config';

export { getLocaleHead } from '@idiomi/react';

export type { IdiomiTypes, Locale } from './.generated/types';
