// Auto-generated by @idiomi/core
// Do not edit directly

import {
  createIdiomiProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idiomi/react/runtime-suspense';
import {
  defaultLocale,
  detection,
  localeParamName,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import type { IdiomiTypes, Locale } from './.generated/types';

export { locales, defaultLocale } from './.generated/config';

export { getLocaleHead } from '@idiomi/react';

const config = {
  locales: ['en', 'es'] as const,
};

export const Trans = createTransSuspense<IdiomiTypes>(config);

export const useT = createUseTSuspense<IdiomiTypes>(config);

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();

export type { IdiomiTypes, Locale };
