// Auto-generated by @idiomi/core
// Do not edit directly
// Middleware exports for Next.js edge runtime

import { createMiddlewareFactory } from '@idiomi/next/middleware';
import { defaultLocale, locales } from './.generated/config';

export const createMiddleware = createMiddlewareFactory({
  locales,
  defaultLocale,
});
