// Auto-generated by @idiomi/core
// Do not edit directly
// Client-only exports for Next.js

'use client';

import { createLink, createLocaleHead } from '@idiomi/next';
import {
  defaultLocale,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';

export const Link = createLink({
  defaultLocale,
  prefixStrategy,
});

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  prefixStrategy,
});
