import { promises as fs } from 'fs';
import { basename, join } from 'path';
import { analyzeIcuMessage, compileIcuToFunction } from '../icu/compiler';
import { loadPoFile } from '../po/parser';
import type { Catalog, Message } from '../po/types';

export interface CompileOptions {
  /** Directory containing .po files */
  localeDir: string;
  /** Output directory for compiled translations */
  outputDir: string;
  /** Default/source locale */
  defaultLocale: string;
}

export interface CompiledMessage {
  /** The message key */
  key: string;
  /** Translations by locale (string or compiled function as string) */
  translations: Record<string, string>;
  /** Whether this message has ICU formatting (needs function compilation) */
  isIcu: boolean;
  /** Variable names used in the message */
  variables: string[];
  /** Number of component tags (<0>...</0>, <1>...</1>, etc.) */
  componentCount: number;
}

/**
 * Count component tags in a message (e.g., <0>...</0>, <1>...</1>).
 * Returns the count of unique tags (max index + 1).
 */
function countComponentTags(source: string): number {
  const tagRegex = /<(\d+)>/g;
  let maxIndex = -1;
  let match;
  while ((match = tagRegex.exec(source)) !== null) {
    const index = parseInt(match[1]!, 10);
    maxIndex = Math.max(maxIndex, index);
  }
  return maxIndex + 1;
}

/**
 * Compile PO files to JavaScript/TypeScript output.
 *
 * Creates:
 * - translations.js: Compiled translation data
 * - types.ts: TypeScript type definitions
 * - index.ts: Re-exports with typed factories
 */
export async function compileTranslations(
  options: CompileOptions,
): Promise<void> {
  const { localeDir, outputDir, defaultLocale } = options;

  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  // Find all .po files
  const files = await fs.readdir(localeDir);
  const poFiles = files.filter((f) => f.endsWith('.po'));

  if (poFiles.length === 0) {
    throw new Error(`No .po files found in ${localeDir}`);
  }

  // Load all catalogs
  const catalogs = new Map<string, Catalog>();
  for (const file of poFiles) {
    const locale = basename(file, '.po');
    const catalog = await loadPoFile(join(localeDir, file), locale);
    catalogs.set(locale, catalog);
  }

  // Collect all unique message keys across catalogs
  const allMessages = new Map<string, CompiledMessage>();

  for (const [locale, catalog] of catalogs) {
    for (const [key, message] of catalog.messages) {
      if (!allMessages.has(key)) {
        const analysis = analyzeIcuMessage(message.source);
        allMessages.set(key, {
          key,
          translations: {},
          isIcu: analysis.hasPlural || analysis.hasSelect,
          variables: analysis.variables,
          componentCount: countComponentTags(message.source),
        });
      }

      const compiled = allMessages.get(key)!;

      // Compile the translation
      if (message.translation) {
        if (compiled.isIcu || message.flags?.includes('icu-format')) {
          // Compile ICU to function string
          compiled.translations[locale] = compileIcuToFunctionString(
            message.translation,
            locale,
          );
          compiled.isIcu = true;
        } else {
          compiled.translations[locale] = message.translation;
        }
      }
    }
  }

  // Generate output files
  await generateTranslationsJs(outputDir, allMessages);
  await generateTypesTs(outputDir, allMessages, [...catalogs.keys()]);
  await generateIndexTs(outputDir);
}

/**
 * Compile ICU message to a function string (for inline in JS)
 */
function compileIcuToFunctionString(message: string, locale: string): string {
  // For now, we'll inline the ICU runtime
  // In production, this would be optimized to conditionals
  const analysis = analyzeIcuMessage(message);

  if (!analysis.hasPlural && !analysis.hasSelect) {
    // Simple string with placeholders - use template literal
    return message.replace(/\{([^}]+)\}/g, '${args.$1}');
  }

  // For ICU with plural/select, generate a function
  // This is a simplified version - full implementation would use the ICU compiler
  return `(args) => {
    const pr = new Intl.PluralRules('${locale}')
    ${generatePluralFunction(message, analysis.variables)}
  }`;
}

function generatePluralFunction(message: string, variables: string[]): string {
  // Simplified plural function generation
  // Full implementation would parse the ICU and generate optimal code
  return `return ${JSON.stringify(message)}.replace(/{(\\w+)}/g, (_, k) => args[k] || '')`;
}

async function generateTranslationsJs(
  outputDir: string,
  messages: Map<string, CompiledMessage>,
): Promise<void> {
  let content = '// Auto-generated by @idioma/core\n';
  content += '// Do not edit directly\n\n';
  content += 'export const translations = {\n';

  for (const [key, msg] of messages) {
    content += `  ${JSON.stringify(key)}: {\n`;
    for (const [locale, translation] of Object.entries(msg.translations)) {
      if (msg.isIcu && translation.startsWith('(args)')) {
        // Function translation
        content += `    ${JSON.stringify(locale)}: ${translation},\n`;
      } else {
        content += `    ${JSON.stringify(locale)}: ${JSON.stringify(translation)},\n`;
      }
    }
    content += '  },\n';
  }

  content += '};\n';

  await fs.writeFile(join(outputDir, 'translations.js'), content, 'utf-8');
}

async function generateTypesTs(
  outputDir: string,
  messages: Map<string, CompiledMessage>,
  locales: string[],
): Promise<void> {
  let content = '// Auto-generated by @idioma/core\n';
  content += '// Do not edit directly\n\n';
  content += "import type { ComponentType, ReactNode } from 'react';\n\n";

  // TransComponent type (for component interpolation)
  content +=
    'export type TransComponent = ComponentType<{ children?: ReactNode }>;\n\n';

  // Generate Locale type
  content += `export type Locale = ${locales.map((l) => JSON.stringify(l)).join(' | ')};\n\n`;

  // Generate TranslationKey type
  const keys = [...messages.keys()];
  content += `export type TranslationKey = ${keys.map((k) => JSON.stringify(k)).join(' | ') || 'never'};\n\n`;

  // Generate MessageValues interface (all keys, empty object for no variables)
  content += 'export interface MessageValues {\n';
  for (const [key, msg] of messages) {
    if (msg.variables.length > 0) {
      const entries = msg.variables
        .map((v) => `${quoteIfNeeded(v)}: string | number`)
        .join('; ');
      content += `  ${JSON.stringify(key)}: { ${entries} };\n`;
    } else {
      content += `  ${JSON.stringify(key)}: Record<string, never>;\n`;
    }
  }
  content += '}\n\n';

  // Generate MessageComponents interface
  content += 'export interface MessageComponents {\n';
  for (const [key, msg] of messages) {
    if (msg.componentCount > 0) {
      const tuple = Array(msg.componentCount).fill('TransComponent').join(', ');
      content += `  ${JSON.stringify(key)}: [${tuple}];\n`;
    } else {
      content += `  ${JSON.stringify(key)}: [];\n`;
    }
  }
  content += '}\n\n';

  // Generate StringOnlyKey type (messages without component tags - can use useT)
  const stringOnlyKeys = [...messages.entries()]
    .filter(([, m]) => m.componentCount === 0)
    .map(([k]) => k);

  content += `export type StringOnlyKey = ${stringOnlyKeys.map((k) => JSON.stringify(k)).join(' | ') || 'never'};\n`;

  await fs.writeFile(join(outputDir, 'types.ts'), content, 'utf-8');
}

/**
 * Quote a variable name if it contains special characters.
 */
function quoteIfNeeded(name: string): string {
  if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
    return name;
  }
  return JSON.stringify(name);
}

async function generateIndexTs(outputDir: string): Promise<void> {
  const content = `// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTrans,
  createUseLocale,
  createUseT,
  Plural,
  plural,
} from '@idioma/react';
import { translations } from './translations.js';
import type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
} from './types';

export const Trans = createTrans<TranslationKey, MessageValues, MessageComponents>(translations);
export const useT = createUseT<StringOnlyKey, MessageValues>(translations);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export { Plural, plural };
export type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
};
`;

  await fs.writeFile(join(outputDir, 'index.ts'), content, 'utf-8');
}
