import { promises as fs } from 'fs';
import { join } from 'path';
import type { Catalog } from '../po/types';
import type { ChunkAnalysis } from './chunk-analysis';

export interface GenerateChunksOptions {
  /** Output directory for compiled translations */
  outputDir: string;
  /** All supported locales */
  locales: string[];
  /** Chunk analysis from extracted messages */
  analysis: ChunkAnalysis;
  /** Loaded catalogs by locale */
  catalogs: Map<string, Catalog>;
}

/**
 * Generate chunk modules for Suspense-based lazy loading.
 *
 * Creates one file per (chunk × locale) combination:
 * - idioma/chunks/HomePage_abc12345.en.ts
 * - idioma/chunks/HomePage_abc12345.es.ts
 * - etc.
 *
 * Also generates a manifest.json for debugging.
 */
export async function generateChunkModules(
  options: GenerateChunksOptions,
): Promise<void> {
  const { outputDir, locales, analysis, catalogs } = options;

  const chunksDir = join(outputDir, 'chunks');
  await fs.mkdir(chunksDir, { recursive: true });

  // Generate one file per (chunk × locale)
  for (const [filePath, { chunkId, keys }] of analysis.files) {
    for (const locale of locales) {
      const translations: Record<string, string> = {};

      for (const key of keys) {
        const msg = catalogs.get(locale)?.messages.get(key);
        translations[key] = msg?.translation ?? '';
      }

      const outputPath = join(chunksDir, `${chunkId}.${locale}.ts`);
      const content = `// Auto-generated by @idioma/core
export default ${JSON.stringify(translations, null, 2)} as const
`;
      await fs.writeFile(outputPath, content, 'utf-8');
    }
  }

  // Generate manifest for debugging
  const manifest = {
    chunks: Object.fromEntries(
      [...analysis.files].map(([filePath, { chunkId }]) => [chunkId, filePath]),
    ),
  };
  await fs.writeFile(
    join(outputDir, 'manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf-8',
  );
}
