import { promises as fs } from 'fs';
import { join } from 'path';
import { analyzeIcuMessage } from '../icu/compiler.js';
import type { Catalog } from '../po/types.js';
import type { ChunkAnalysis } from './chunk-analysis.js';
import { compileIcuToFunctionString } from './compile.js';

export interface GenerateChunksOptions {
  /** Output directory for compiled translations */
  outputDir: string;
  /** All supported locales */
  locales: string[];
  /** Chunk analysis from extracted messages */
  analysis: ChunkAnalysis;
  /** Loaded catalogs by locale */
  catalogs: Map<string, Catalog>;
}

/**
 * Generate chunk modules for Suspense-based lazy loading.
 *
 * Creates one file per (chunk × locale) combination:
 * - idioma/chunks/HomePage_abc12345.en.ts
 * - idioma/chunks/HomePage_abc12345.es.ts
 * - etc.
 *
 * Also generates a manifest.json for debugging.
 */
export async function generateChunkModules(
  options: GenerateChunksOptions,
): Promise<void> {
  const { outputDir, locales, analysis, catalogs } = options;

  const chunksDir = join(outputDir, 'chunks');
  await fs.mkdir(chunksDir, { recursive: true });

  // Generate one file per (chunk × locale)
  for (const [filePath, { chunkId, keys }] of analysis.files) {
    for (const locale of locales) {
      const translations: Record<string, string> = {};
      const hasIcuMessage = new Set<string>();

      for (const key of keys) {
        const msg = catalogs.get(locale)?.messages.get(key);
        const translation = msg?.translation ?? '';

        if (translation) {
          // Check if message has component tags (they break ICU parser)
          const hasComponentTags = /<\d+>/.test(translation);

          if (!hasComponentTags) {
            // Analyze for ICU patterns (plural, select)
            try {
              const analysis = analyzeIcuMessage(translation);
              if (analysis.hasPlural || analysis.hasSelect) {
                // Compile ICU to function string
                translations[key] = compileIcuToFunctionString(
                  translation,
                  locale,
                );
                hasIcuMessage.add(key);
              } else {
                translations[key] = translation;
              }
            } catch {
              // If parsing fails, treat as plain string
              translations[key] = translation;
            }
          } else {
            translations[key] = translation;
          }
        } else {
          translations[key] = '';
        }
      }

      // Generate chunk file with proper serialization for functions
      const outputPath = join(chunksDir, `${chunkId}.${locale}.ts`);
      const entries = Object.entries(translations).map(([key, value]) => {
        if (hasIcuMessage.has(key)) {
          // Function - use the compiled function string directly
          return `  "${key}": ${value}`;
        }
        // String - quote it
        return `  "${key}": ${JSON.stringify(value)}`;
      });

      const content = `// Auto-generated by @idioma/core
export default {
${entries.join(',\n')}
}
`;
      await fs.writeFile(outputPath, content, 'utf-8');
    }
  }

  // Generate manifest for debugging
  const manifest = {
    chunks: Object.fromEntries(
      [...analysis.files].map(([filePath, { chunkId }]) => [chunkId, filePath]),
    ),
  };
  await fs.writeFile(
    join(outputDir, 'manifest.json'),
    JSON.stringify(manifest, null, 2),
    'utf-8',
  );
}
