/**
 * Generates .generated/config.js and config.d.ts for runtime config access.
 *
 * These files provide the compiled idiomi.config.ts values to generated code,
 * avoiding hardcoded values that could drift from the source config.
 */

export interface DetectionOptions {
  /** Cookie name for storing locale preference */
  cookieName?: string;
  /** Detection priority order */
  order?: Array<'cookie' | 'header'>;
  /**
   * Locale matching algorithm for Accept-Language header.
   * - 'best fit': Uses language distance (e.g., en-GB matches en-US)
   * - 'lookup': Strict RFC 4647 matching
   * @default 'best fit'
   */
  algorithm?: 'lookup' | 'best fit';
}

export interface ConfigGeneratorOptions {
  /** All supported locales */
  locales: string[];
  /** Default/source locale */
  defaultLocale: string;
  /**
   * Locale prefix strategy for URLs.
   * @default 'as-needed'
   */
  prefixStrategy?: 'always' | 'as-needed' | 'never';
  /** Detection settings */
  detection?: DetectionOptions;
}

/**
 * Generate .generated/config.js content.
 *
 * @example Output:
 * ```javascript
 * export const locales = ["en","es","fr"];
 * export const defaultLocale = "en";
 * export const prefixStrategy = "as-needed";
 * export const detection = {
 *   "order": ["cookie","header"],
 *   "cookieName": "IDIOMI_LOCALE",
 *   "algorithm": "best fit"
 * };
 * ```
 */
export function generateConfigModule(options: ConfigGeneratorOptions): string {
  const {
    locales,
    defaultLocale,
    prefixStrategy = 'as-needed',
    detection = {},
  } = options;

  const {
    order = ['cookie', 'header'],
    cookieName = 'IDIOMI_LOCALE',
    algorithm = 'best fit',
  } = detection;

  const lines = [
    '// Auto-generated by @idiomi/core',
    '// Do not edit directly',
    '',
    `export const locales = ${JSON.stringify(locales)};`,
    `export const defaultLocale = ${JSON.stringify(defaultLocale)};`,
    `export const prefixStrategy = ${JSON.stringify(prefixStrategy)};`,
    `export const detection = ${JSON.stringify({ order, cookieName, algorithm })};`,
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate .generated/config.d.ts content.
 *
 * @example Output:
 * ```typescript
 * export declare const locales: readonly ["en", "es", "fr"];
 * export declare const defaultLocale: "en";
 * export declare const prefixStrategy: "always" | "as-needed" | "never";
 * export declare const detection: {
 *   readonly order: readonly ("cookie" | "header")[];
 *   readonly cookieName: string;
 *   readonly algorithm: "lookup" | "best fit";
 * };
 * ```
 */
export function generateConfigTypes(options: ConfigGeneratorOptions): string {
  const { locales, defaultLocale } = options;

  const localesTuple = locales.map((l) => JSON.stringify(l)).join(', ');

  const lines = [
    '// Auto-generated by @idiomi/core',
    '// Do not edit directly',
    '',
    `export declare const locales: readonly [${localesTuple}];`,
    `export declare const defaultLocale: ${JSON.stringify(defaultLocale)};`,
    `export declare const prefixStrategy: "always" | "as-needed" | "never";`,
    `export declare const detection: {`,
    `  readonly order: readonly ("cookie" | "header")[];`,
    `  readonly cookieName: string;`,
    `  readonly algorithm: "lookup" | "best fit";`,
    `};`,
    '',
  ];

  return lines.join('\n');
}
