// Auto-generated by @idiomi/core
// Do not edit directly
// Client-only exports for Next.js

'use client';

import { createLink, createLocaleHead } from '@idiomi/next';
import {
  defaultLocale,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import { reverseRoutes, routePatterns, routes } from './.generated/routes';

export const Link = createLink({
  routes,
  routePatterns,
  defaultLocale,
  prefixStrategy,
});

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  routes,
  reverseRoutes,
  routePatterns,
  prefixStrategy,
});
