// Auto-generated by @idiomi/core
// Do not edit directly
// Client-only exports for Next.js

'use client';

import { createLink, createLocaleHead } from '@idiomi/next/pages';
import {
  createIdiomiProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idiomi/react';
import {
  defaultLocale,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import { reverseRoutes, routePatterns, routes } from './.generated/routes';
import type { IdiomiTypes, Locale } from './.generated/types';

export const Link = createLink({
  routes,
  routePatterns,
  defaultLocale,
  prefixStrategy,
});

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  routes,
  reverseRoutes,
  routePatterns,
  prefixStrategy,
});

export const Trans = createTrans<IdiomiTypes>();

export const useT = createUseT<IdiomiTypes>();

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();
