// Auto-generated by @idiomi/core
// Do not edit directly
// Client-only exports for Next.js

'use client';

import { createLink, createLocaleHead } from '@idiomi/next/pages';
import {
  createIdiomiProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idiomi/react/runtime-suspense';
import {
  defaultLocale,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import type { IdiomiTypes, Locale } from './.generated/types';

export const Link = createLink({
  defaultLocale,
  prefixStrategy,
});

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  prefixStrategy,
});

const config = {
  locales: ['en', 'es'] as const,
};

export const Trans = createTransSuspense<IdiomiTypes>(config);

export const useT = createUseTSuspense<IdiomiTypes>(config);

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();
