import { useCallback, useContext } from 'react';
import { IdiomaContext } from './context';
import { interpolateValues } from './interpolate';

type MessageFunction = (args: Record<string, unknown>) => string;

// =============================================================================
// IdiomaTypes - Single type parameter for cleaner API
// =============================================================================

/**
 * Base interface for project-specific Idioma types.
 * Generated by the compiler in types.d.ts.
 *
 * @example
 * // In generated types.d.ts:
 * export interface IdiomaTypes {
 *   TranslationKey: 'greeting' | 'farewell';
 *   MessageValues: { greeting: { name: string } };
 *   MessageComponents: { greeting: [] };
 * }
 */
export interface BaseIdiomaConfig {
  TranslationKey: string;
  MessageValues: Record<string, Record<string, unknown>>;
  MessageComponents: Record<string, unknown[]>;
}

// =============================================================================
// Helper Types for Strict Typing
// =============================================================================

// --- Key-only mode helpers ---

/** Keys in MessageValues that have at least one required value */
export type KeysWithValues<MV extends Record<string, Record<string, unknown>>> =
  {
    [K in keyof MV]: MV[K] extends Record<string, never> ? never : K;
  }[keyof MV];

/** Keys in MessageValues that have no required values */
export type KeysWithoutValues<
  MV extends Record<string, Record<string, unknown>>,
> = {
  [K in keyof MV]: MV[K] extends Record<string, never> ? K : never;
}[keyof MV];

/**
 * Derive string-only keys from TranslationKey + MessageComponents.
 * Keys with empty component arrays [] can be used with useT.
 * Keys with non-empty component arrays [TransComponent, ...] must use Trans.
 */
export type StringOnlyKeys<
  TK extends string,
  MC extends Record<string, unknown[]>,
> = {
  [K in TK & keyof MC]: MC[K] extends [] ? K : never;
}[TK & keyof MC];

// --- Source text mode helpers ---

/**
 * Recursively extract placeholder names from a template string.
 * "Hello {name}, you have {count} items" → "name" | "count"
 */
export type ExtractPlaceholders<S extends string> =
  S extends `${infer _}{${infer Key}}${infer Rest}`
    ? Key | ExtractPlaceholders<Rest>
    : never;

/**
 * Build the required values object from extracted placeholders.
 * "Hello {name}" → { name: string | number }
 * "No placeholders" → undefined
 */
export type PlaceholderValues<S extends string> =
  ExtractPlaceholders<S> extends never
    ? undefined
    : { [K in ExtractPlaceholders<S>]: string | number };

/** Check if a string has any placeholders */
export type HasPlaceholders<S extends string> =
  ExtractPlaceholders<S> extends never ? false : true;

/**
 * Source text mode options: t("Submit", undefined, { context: "button", ns: "common" })
 */
export interface SourceTextOptions {
  /** Translator context (changes key hash) */
  context?: string;
  /** Translator comment (extracted to PO #. comment for translators) */
  comment?: string;
  /** Namespace for scoped lookups (placeholder for future) */
  ns?: string;
}

/**
 * Type for the t function returned by useT.
 * Supports both source text mode and key-only mode with full type safety.
 *
 * @template C - IdiomaTypes interface containing TranslationKey, MessageValues, MessageComponents
 *
 * The TFunction only accepts keys where MessageComponents[K] is an empty array (string-only keys).
 */
export type TFunction<C extends BaseIdiomaConfig = BaseIdiomaConfig> = {
  // === Key-only mode ===

  // Keys that require values (only string-only keys allowed)
  <
    K extends StringOnlyKeys<C['TranslationKey'], C['MessageComponents']> &
      string,
  >(
    args: K extends KeysWithValues<C['MessageValues']>
      ? {
          id: K;
          values: C['MessageValues'][K];
          source?: string;
          context?: string;
          ns?: string;
        }
      : K extends KeysWithoutValues<C['MessageValues']>
        ? {
            id: K;
            values?: never;
            source?: string;
            context?: string;
            ns?: string;
          }
        : {
            id: K;
            values?: Record<string, unknown>;
            source?: string;
            context?: string;
            ns?: string;
          },
  ): string;

  // === Source text mode ===

  // Source text WITH placeholders - values required
  <S extends string>(
    source: HasPlaceholders<S> extends true ? S : never,
    values: PlaceholderValues<S>,
  ): string;

  // Source text WITHOUT placeholders - no values
  <S extends string>(
    source: HasPlaceholders<S> extends false ? S : never,
  ): string;

  // Source text with options (3rd arg)
  <S extends string>(
    source: S,
    values: PlaceholderValues<S>,
    options: SourceTextOptions,
  ): string;
};

/**
 * Creates a typed useT hook for imperative translations.
 *
 * Supports both source text mode and key-only mode:
 * - Source text: t('Hello world!') - hashes and looks up
 * - Key-only: t({ id: 'welcome' }) - direct key lookup
 *
 * Only works with messages that don't require component interpolation,
 * since it returns a string. For messages with <0>...</0> tags, use <Trans>.
 *
 * @example
 * // In generated idioma/index.ts:
 * export const useT = createUseT<IdiomaTypes>()
 *
 * // Usage:
 * const t = useT()
 * t('Hello world!')  // source text mode
 * t('Hello {name}', { name: 'Ben' })  // with values (2nd arg)
 * t('Submit', undefined, { context: 'button' })  // with options (3rd arg)
 * t('Hello {name}', { name: 'Ben' }, { context: 'greeting' })  // both
 * t({ id: 'welcome' })  // key-only mode
 * t({ id: 'greeting', values: { name: 'Ben' }, ns: 'common' })  // with ns
 */
// Internal runtime type for key-only args (untyped at runtime)
interface KeyOnlyArgsRuntime {
  id: string;
  source?: string;
  values?: Record<string, unknown>;
  context?: string;
  ns?: string;
}

export function createUseT<
  C extends BaseIdiomaConfig = BaseIdiomaConfig,
>(): () => TFunction<C> {
  /**
   * useT hook for imperative translations.
   *
   * Babel transforms t() calls to include inlined translations.
   * This hook handles the transformed calls and provides fallback behavior.
   */
  return function useT(): TFunction<C> {
    const ctx = useContext(IdiomaContext);
    if (!ctx) {
      throw new Error(
        '[idioma] useT must be used within an IdiomaProvider. ' +
          'Make sure to wrap your app with <IdiomaProvider>.',
      );
    }

    const { locale } = ctx;

    return useCallback(
      (
        sourceOrArgs: string | KeyOnlyArgsRuntime,
        values?: Record<string, unknown>,
        options?: SourceTextOptions,
      ): string => {
        // Key-only mode: t({ id: 'welcome', source: 'Hello', values: { name }, ns: 'common' })
        // Babel should transform this, but if not, use source as fallback text
        if (typeof sourceOrArgs === 'object') {
          const { id, source, values: objValues } = sourceOrArgs;
          console.warn(
            `[idioma] t({ id: "${id}" }) was not transformed by Babel. ` +
              'Make sure @idioma/core Babel plugin is configured.',
          );
          const fallbackText = source || id;
          if (objValues && Object.keys(objValues).length > 0) {
            return interpolateValues(fallbackText, objValues);
          }
          return fallbackText;
        }

        // Source text mode: t('Hello {name}', { name: 'Ben' }, { context: 'button' })
        // OR after Babel transformation: t('Hello {name}', { key: { en: '...', es: '...' } }, { name: 'Ben' })
        const source = sourceOrArgs;

        // Detect if Babel has inlined translations in arg 2
        // Babel transforms: t('src', { key: { en: '...', es: '...' } }, { actualValues })
        // The inlined object has ONE key (the message key) whose value has locale keys
        let actualValues = values;
        let localeMessages:
          | Record<string, string | MessageFunction>
          | undefined;

        const valuesKeys = values ? Object.keys(values) : [];
        const firstKey = valuesKeys[0];
        const firstValue =
          firstKey && values
            ? (values as Record<string, unknown>)[firstKey]
            : undefined;

        // Check if this looks like Babel-inlined translations:
        // - Has exactly one key (the message key)
        // - That key's value is an object with locale as a property
        if (
          valuesKeys.length === 1 &&
          firstValue &&
          typeof firstValue === 'object' &&
          typeof (firstValue as Record<string, unknown>)[locale] !== 'undefined'
        ) {
          // Babel transformed: arg 2 is { messageKey: { en: '...', es: '...' } }
          localeMessages = firstValue as Record<
            string,
            string | MessageFunction
          >;
          actualValues = options as unknown as Record<string, unknown>;
        }

        if (!localeMessages) {
          // Not transformed by Babel - fallback to source text
          return actualValues && Object.keys(actualValues).length > 0
            ? interpolateValues(source, actualValues)
            : source;
        }

        const msg = localeMessages[locale] ?? Object.values(localeMessages)[0];
        if (msg === undefined) {
          return actualValues && Object.keys(actualValues).length > 0
            ? interpolateValues(source, actualValues)
            : source;
        }

        if (typeof msg === 'function') {
          return msg(actualValues || {});
        }

        return actualValues && Object.keys(actualValues).length > 0
          ? interpolateValues(msg, actualValues)
          : msg;
      },
      [locale],
    ) as TFunction<C>;
  };
}
