// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idioma/react/runtime-suspense';
import type {
  Locale,
  MessageComponents,
  MessageValues,
  TranslationKey,
} from './.generated/types';

const config = {
  locales: ["en","es"] as const,
};

export const Trans = createTransSuspense<TranslationKey, MessageValues, MessageComponents>(config);
export const useT = createUseTSuspense<TranslationKey, MessageValues, MessageComponents>(config);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type {
  Locale,
  MessageComponents,
  MessageValues,
  TranslationKey,
};
