// Auto-generated by @idiomi/core
import { _createTFactory } from '@idiomi/core/runtime';
import type { Locale, MessageValues, TranslationKey } from './.generated/types';

export const createT = (locale: Locale) =>
  _createTFactory<TranslationKey, MessageValues>(locale);

export type { Locale, TranslationKey, MessageValues };
