// Auto-generated by @idioma/core
import { _createTFactory } from '@idioma/core/runtime';
import type { Locale, StringOnlyKey, MessageValues } from './.generated/types';

export const createT = (locale: Locale) =>
  _createTFactory<StringOnlyKey, MessageValues>(locale);

export type { Locale, StringOnlyKey, MessageValues };
