// Auto-generated by @idiomi/core
// Do not edit directly

import {
  createIdiomiProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idiomi/react/runtime-suspense';
import type { IdiomiTypes, Locale } from './.generated/types';

const config = {
  locales: ["en","es","ar"] as const,
};

export const Trans = createTransSuspense<IdiomiTypes>(config);
export const useT = createUseTSuspense<IdiomiTypes>(config);
export const IdiomiProvider = createIdiomiProvider();
export const useLocale = createUseLocale();

export type { IdiomiTypes, Locale };
