import type { Message } from '../po/types.js';
import type {
  CompiledRoutes,
  ExtractedRoute,
  Framework,
  RoutePattern,
} from './types.js';
import { isDynamicSegment } from './types.js';

/** Route context prefix in PO files */
export const ROUTE_CONTEXT_PREFIX = 'route:';

/**
 * Compile route translations from PO messages.
 *
 * Takes extracted routes and translated PO messages to produce:
 * 1. Segment translations: { en: { about: 'about' }, es: { about: 'sobre' } }
 * 2. Full route maps: { en: { '/about': '/about' }, es: { '/about': '/sobre' } }
 * 3. Reverse maps: { es: { '/sobre': '/about' } }
 *
 * @param routes - Routes extracted from the project
 * @param messages - Messages per locale from PO files (only route: context entries)
 * @param locales - List of supported locales
 * @param framework - Framework type for dynamic segment detection
 */
export function compileRoutes(
  routes: ExtractedRoute[],
  messages: Record<string, Message[]>,
  locales: string[],
  framework: Framework,
): CompiledRoutes {
  // Step 1: Build segment translation maps from PO messages
  const segments: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    segments[locale] = {};

    const localeMessages = messages[locale] ?? [];

    for (const msg of localeMessages) {
      // Only process route context messages
      if (!msg.context?.startsWith(ROUTE_CONTEXT_PREFIX)) {
        continue;
      }

      // Extract segment name from context (e.g., "route:about" → "about")
      const segment = msg.context.slice(ROUTE_CONTEXT_PREFIX.length);

      // Only use non-empty translations, don't overwrite existing with empty fallbacks
      // This handles duplicate route entries where one has translation and one doesn't
      if (msg.translation) {
        segments[locale][segment] = msg.translation;
      } else if (!segments[locale][segment]) {
        // Fallback to segment name only if no translation yet
        segments[locale][segment] = segment;
      }
    }
  }

  // Step 2: Build full route maps by translating each route's segments
  const routeMaps: Record<string, Record<string, string>> = {};
  const reverseMaps: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    routeMaps[locale] = {};
    reverseMaps[locale] = {};
  }

  for (const route of routes) {
    const canonicalPath = route.path;

    for (const locale of locales) {
      const localeSegments = segments[locale] ?? {};
      const localeRoutes = routeMaps[locale] ?? {};
      const localeReverse = reverseMaps[locale] ?? {};

      // Translate each segment of the path
      const translatedSegments = route.segments.map((seg) => {
        // Dynamic segments are preserved as-is
        if (isDynamicSegment(seg, framework)) {
          return seg;
        }
        // Look up translation, fall back to original
        return localeSegments[seg] ?? seg;
      });

      const translatedPath =
        translatedSegments.length > 0
          ? `/${translatedSegments.join('/')}`
          : '/';

      localeRoutes[canonicalPath] = translatedPath;
      localeReverse[translatedPath] = canonicalPath;
    }
  }

  // Step 3: Build patterns array for segment-level matching
  // Patterns allow matching concrete URLs against parameterized routes
  // by tracking which segments are dynamic vs static
  const patterns: RoutePattern[] = routes.map((route) => ({
    canonical: route.segments,
    localized: Object.fromEntries(
      locales.map((locale) => [
        locale,
        route.segments.map((seg) =>
          isDynamicSegment(seg, framework)
            ? seg
            : (segments[locale]?.[seg] ?? seg),
        ),
      ]),
    ),
  }));

  return {
    routes: routeMaps,
    reverseRoutes: reverseMaps,
    patterns,
  };
}

/**
 * Generate JavaScript code for the compiled routes.
 *
 * @param compiled - The compiled route maps
 * @returns JavaScript module source code
 */
export function generateRoutesModule(compiled: CompiledRoutes): string {
  const lines: string[] = [
    '// Auto-generated by @idiomi/core - DO NOT EDIT',
    '// This file contains compiled route translations',
    '',
    '/** Canonical path → Localized path by locale */',
    `export const routes = ${JSON.stringify(compiled.routes, null, 2)};`,
    '',
    '/** Localized path → Canonical path by locale (for URL matching) */',
    `export const reverseRoutes = ${JSON.stringify(compiled.reverseRoutes, null, 2)};`,
    '',
    '/** Route patterns for segment-level matching with dynamic params */',
    `export const routePatterns = ${JSON.stringify(compiled.patterns, null, 2)};`,
    '',
    '/**',
    ' * Match a URL path against route patterns.',
    ' * Returns captured dynamic param values and the matching pattern, or null if no match.',
    ' */',
    'function matchRoutePattern(segments, useLocalized, locale) {',
    '  for (const pattern of routePatterns) {',
    '    const patternSegs = useLocalized ? pattern.localized[locale] : pattern.canonical;',
    '    if (!patternSegs || patternSegs.length !== segments.length) continue;',
    '',
    '    const captured = {};',
    '    let matches = true;',
    '',
    '    for (let i = 0; i < patternSegs.length; i++) {',
    '      const patternSeg = patternSegs[i];',
    '      const urlSeg = segments[i];',
    '',
    "      if (patternSeg.startsWith('$')) {",
    '        captured[patternSeg] = urlSeg;',
    '      } else if (patternSeg !== urlSeg) {',
    '        matches = false;',
    '        break;',
    '      }',
    '    }',
    '',
    '    if (matches) {',
    '      return { pattern, captured };',
    '    }',
    '  }',
    '  return null;',
    '}',
    '',
    '/** Get localized path for a canonical path (supports dynamic params) */',
    'export function getLocalizedPath(canonicalPath, locale) {',
    '  // Try direct lookup first (fastest for static routes)',
    '  const direct = routes[locale]?.[canonicalPath];',
    '  if (direct) return direct;',
    '',
    '  // Handle root path',
    "  if (canonicalPath === '/') return '/';",
    '',
    '  // Parse path into segments and try pattern matching',
    "  const segments = canonicalPath.split('/').filter(Boolean);",
    '  const match = matchRoutePattern(segments, false, locale);',
    '',
    '  if (match) {',
    '    const localizedSegs = match.pattern.localized[locale];',
    '    if (localizedSegs) {',
    "      return '/' + localizedSegs.map(seg =>",
    "        seg.startsWith('$') ? match.captured[seg] : seg",
    "      ).join('/');",
    '    }',
    '  }',
    '',
    '  return canonicalPath;',
    '}',
    '',
    '/** Get canonical path from a localized path (supports dynamic params) */',
    'export function getCanonicalPath(localizedPath, locale) {',
    '  // Try direct lookup first (fastest for static routes)',
    '  const direct = reverseRoutes[locale]?.[localizedPath];',
    '  if (direct) return direct;',
    '',
    '  // Handle root path',
    "  if (localizedPath === '/') return '/';",
    '',
    '  // Parse path into segments and try pattern matching',
    "  const segments = localizedPath.split('/').filter(Boolean);",
    '  const match = matchRoutePattern(segments, true, locale);',
    '',
    '  if (match) {',
    "    return '/' + match.pattern.canonical.map(seg =>",
    "      seg.startsWith('$') ? match.captured[seg] : seg",
    "    ).join('/');",
    '  }',
    '',
    '  return localizedPath;',
    '}',
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate TypeScript declarations for the routes module.
 */
export function generateRoutesTypes(locales: string[]): string {
  const localeUnion = locales.map((l) => `'${l}'`).join(' | ');

  return `// Auto-generated by @idiomi/core - DO NOT EDIT

export type Locale = ${localeUnion};

export interface RoutePattern {
  canonical: string[];
  localized: Record<Locale, string[]>;
}

export declare const routes: Record<Locale, Record<string, string>>;
export declare const reverseRoutes: Record<Locale, Record<string, string>>;
export declare const routePatterns: RoutePattern[];

export declare function getLocalizedPath(canonicalPath: string, locale: Locale): string;
export declare function getCanonicalPath(localizedPath: string, locale: Locale): string;
`;
}
