import type { Message } from '../po/types.js';
import type {
  CompiledRoutes,
  ExtractedRoute,
  Framework,
  RoutePattern,
} from './types.js';
import { isDynamicSegment } from './types.js';

/** Route context prefix in PO files */
export const ROUTE_CONTEXT_PREFIX = 'route:';

/**
 * Compile route translations from PO messages.
 *
 * Takes extracted routes and translated PO messages to produce:
 * 1. Segment translations: { en: { about: 'about' }, es: { about: 'sobre' } }
 * 2. Full route maps: { en: { '/about': '/about' }, es: { '/about': '/sobre' } }
 * 3. Reverse maps: { es: { '/sobre': '/about' } }
 *
 * @param routes - Routes extracted from the project
 * @param messages - Messages per locale from PO files (only route: context entries)
 * @param locales - List of supported locales
 * @param framework - Framework type for dynamic segment detection
 */
export function compileRoutes(
  routes: ExtractedRoute[],
  messages: Record<string, Message[]>,
  locales: string[],
  framework: Framework,
): CompiledRoutes {
  // Step 1: Build segment translation maps from PO messages
  const segments: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    segments[locale] = {};

    const localeMessages = messages[locale] ?? [];

    for (const msg of localeMessages) {
      // Only process route context messages
      if (!msg.context?.startsWith(ROUTE_CONTEXT_PREFIX)) {
        continue;
      }

      // Extract segment name from context (e.g., "route:about" → "about")
      const segment = msg.context.slice(ROUTE_CONTEXT_PREFIX.length);

      // Only use non-empty translations, don't overwrite existing with empty fallbacks
      // This handles duplicate route entries where one has translation and one doesn't
      if (msg.translation) {
        segments[locale][segment] = msg.translation;
      } else if (!segments[locale][segment]) {
        // Fallback to segment name only if no translation yet
        segments[locale][segment] = segment;
      }
    }
  }

  // Step 2: Build full route maps by translating each route's segments
  const routeMaps: Record<string, Record<string, string>> = {};
  const reverseMaps: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    routeMaps[locale] = {};
    reverseMaps[locale] = {};
  }

  for (const route of routes) {
    const canonicalPath = route.path;

    for (const locale of locales) {
      const localeSegments = segments[locale] ?? {};
      const localeRoutes = routeMaps[locale] ?? {};
      const localeReverse = reverseMaps[locale] ?? {};

      // Translate each segment of the path
      const translatedSegments = route.segments.map((seg) => {
        // Dynamic segments are preserved as-is
        if (isDynamicSegment(seg, framework)) {
          return seg;
        }
        // Look up translation, fall back to original
        return localeSegments[seg] ?? seg;
      });

      const translatedPath =
        translatedSegments.length > 0
          ? `/${translatedSegments.join('/')}`
          : '/';

      localeRoutes[canonicalPath] = translatedPath;
      localeReverse[translatedPath] = canonicalPath;
    }
  }

  // Step 3: Build patterns array for segment-level matching
  // Patterns allow matching concrete URLs against parameterized routes
  // by tracking which segments are dynamic vs static
  const patterns: RoutePattern[] = routes.map((route) => ({
    canonical: route.segments,
    localized: Object.fromEntries(
      locales.map((locale) => [
        locale,
        route.segments.map((seg) =>
          isDynamicSegment(seg, framework)
            ? seg
            : (segments[locale]?.[seg] ?? seg),
        ),
      ]),
    ),
  }));

  return {
    routes: routeMaps,
    reverseRoutes: reverseMaps,
    patterns,
  };
}

/**
 * Check if a framework is TanStack-based.
 */
function isTanStackFramework(framework: Framework): boolean {
  return framework === 'tanstack' || framework === 'tanstack-start';
}

/**
 * Generate JavaScript code for the compiled routes.
 *
 * For TanStack: Imports pattern matching from @idiomi/tanstack-react/pattern-matching
 * For Next.js: Only exports static route maps (pattern matching not needed)
 *
 * @param compiled - The compiled route maps
 * @param framework - Target framework
 * @returns JavaScript module source code
 */
export function generateRoutesModule(
  compiled: CompiledRoutes,
  framework: Framework,
): string {
  const lines: string[] = [
    '// Auto-generated by @idiomi/core - DO NOT EDIT',
    '// This file contains compiled route translations',
    '',
  ];

  // TanStack: Import pattern matching from @idiomi/tanstack-react
  if (isTanStackFramework(framework)) {
    lines.push(
      "import { getLocalizedPath as _getLocalizedPath, getCanonicalPath as _getCanonicalPath } from '@idiomi/tanstack-react/pattern-matching';",
      '',
    );
  }

  // Static route maps (always exported)
  lines.push(
    '/** Canonical path → Localized path by locale */',
    `export const routes = ${JSON.stringify(compiled.routes, null, 2)};`,
    '',
    '/** Localized path → Canonical path by locale (for URL matching) */',
    `export const reverseRoutes = ${JSON.stringify(compiled.reverseRoutes, null, 2)};`,
    '',
  );

  // TanStack: Export patterns and wrapper functions
  if (isTanStackFramework(framework)) {
    lines.push(
      '/** Route patterns for segment-level matching with dynamic params */',
      `export const routePatterns = ${JSON.stringify(compiled.patterns, null, 2)};`,
      '',
      '/** Get localized path for a canonical path (supports dynamic params) */',
      'export function getLocalizedPath(canonicalPath, locale) {',
      '  return _getLocalizedPath(canonicalPath, locale, routes, routePatterns);',
      '}',
      '',
      '/** Get canonical path from a localized path (supports dynamic params) */',
      'export function getCanonicalPath(localizedPath, locale) {',
      '  return _getCanonicalPath(localizedPath, locale, reverseRoutes, routePatterns);',
      '}',
      '',
    );
  }

  return lines.join('\n');
}

/**
 * Generate TypeScript declarations for the routes module.
 *
 * For TanStack: Includes routePatterns and helper function types
 * For Next.js: Only includes static route map types
 *
 * @param locales - List of supported locales
 * @param framework - Target framework
 */
export function generateRoutesTypes(
  locales: string[],
  framework: Framework,
): string {
  const localeUnion = locales.map((l) => `'${l}'`).join(' | ');

  const lines = [
    '// Auto-generated by @idiomi/core - DO NOT EDIT',
    '',
    `export type Locale = ${localeUnion};`,
    '',
    'export declare const routes: Record<Locale, Record<string, string>>;',
    'export declare const reverseRoutes: Record<Locale, Record<string, string>>;',
  ];

  // TanStack: Include pattern types and helper functions
  if (isTanStackFramework(framework)) {
    lines.push(
      '',
      'export interface RoutePattern {',
      '  canonical: string[];',
      '  localized: Record<Locale, string[]>;',
      '}',
      '',
      'export declare const routePatterns: RoutePattern[];',
      '',
      'export declare function getLocalizedPath(canonicalPath: string, locale: Locale): string;',
      'export declare function getCanonicalPath(localizedPath: string, locale: Locale): string;',
    );
  }

  lines.push('');

  return lines.join('\n');
}
