import type { Message } from '../po/types.js';
import type { CompiledRoutes, ExtractedRoute } from './types.js';
import { isDynamicSegment } from './types.js';

/** Route context prefix in PO files */
export const ROUTE_CONTEXT_PREFIX = 'route:';

/**
 * Compile route translations from PO messages.
 *
 * Takes extracted routes and translated PO messages to produce:
 * 1. Segment translations: { en: { about: 'about' }, es: { about: 'sobre' } }
 * 2. Full route maps: { en: { '/about': '/about' }, es: { '/about': '/sobre' } }
 * 3. Reverse maps: { es: { '/sobre': '/about' } }
 *
 * @param routes - Routes extracted from the project
 * @param messages - Messages per locale from PO files (only route: context entries)
 * @param locales - List of supported locales
 */
export function compileRoutes(
  routes: ExtractedRoute[],
  messages: Record<string, Message[]>,
  locales: string[],
): CompiledRoutes {
  // Step 1: Build segment translation maps from PO messages
  const segments: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    segments[locale] = {};

    const localeMessages = messages[locale] ?? [];

    for (const msg of localeMessages) {
      // Only process route context messages
      if (!msg.context?.startsWith(ROUTE_CONTEXT_PREFIX)) {
        continue;
      }

      // Extract segment name from context (e.g., "route:about" → "about")
      const segment = msg.context.slice(ROUTE_CONTEXT_PREFIX.length);

      // Use translation if available, otherwise fall back to source
      const translation = msg.translation || msg.source;
      segments[locale][segment] = translation;
    }
  }

  // Step 2: Build full route maps by translating each route's segments
  const routeMaps: Record<string, Record<string, string>> = {};
  const reverseMaps: Record<string, Record<string, string>> = {};

  for (const locale of locales) {
    routeMaps[locale] = {};
    reverseMaps[locale] = {};
  }

  for (const route of routes) {
    const canonicalPath = route.path;

    for (const locale of locales) {
      const localeSegments = segments[locale] ?? {};
      const localeRoutes = routeMaps[locale] ?? {};
      const localeReverse = reverseMaps[locale] ?? {};

      // Translate each segment of the path
      const translatedSegments = route.segments.map((seg) => {
        // Dynamic segments are preserved as-is
        if (isDynamicSegment(seg)) {
          return seg;
        }
        // Look up translation, fall back to original
        return localeSegments[seg] ?? seg;
      });

      const translatedPath =
        translatedSegments.length > 0
          ? `/${translatedSegments.join('/')}`
          : '/';

      localeRoutes[canonicalPath] = translatedPath;
      localeReverse[translatedPath] = canonicalPath;
    }
  }

  return {
    segments,
    routes: routeMaps,
    reverseRoutes: reverseMaps,
  };
}

/**
 * Generate JavaScript code for the compiled routes.
 *
 * @param compiled - The compiled route maps
 * @returns JavaScript module source code
 */
export function generateRoutesModule(compiled: CompiledRoutes): string {
  const lines: string[] = [
    '// Auto-generated by @idiomi/core - DO NOT EDIT',
    '// This file contains compiled route translations',
    '',
    '/** Segment translations by locale */',
    `export const segments = ${JSON.stringify(compiled.segments, null, 2)};`,
    '',
    '/** Canonical path → Localized path by locale */',
    `export const routes = ${JSON.stringify(compiled.routes, null, 2)};`,
    '',
    '/** Localized path → Canonical path by locale (for URL matching) */',
    `export const reverseRoutes = ${JSON.stringify(compiled.reverseRoutes, null, 2)};`,
    '',
    '/** Get localized path for a canonical path */',
    'export function getLocalizedPath(canonicalPath, locale) {',
    '  return routes[locale]?.[canonicalPath] ?? canonicalPath;',
    '}',
    '',
    '/** Get canonical path from a localized path */',
    'export function getCanonicalPath(localizedPath, locale) {',
    '  return reverseRoutes[locale]?.[localizedPath] ?? localizedPath;',
    '}',
    '',
  ];

  return lines.join('\n');
}

/**
 * Generate TypeScript declarations for the routes module.
 */
export function generateRoutesTypes(locales: string[]): string {
  const localeUnion = locales.map((l) => `'${l}'`).join(' | ');

  return `// Auto-generated by @idiomi/core - DO NOT EDIT

export type Locale = ${localeUnion};

export declare const segments: Record<Locale, Record<string, string>>;
export declare const routes: Record<Locale, Record<string, string>>;
export declare const reverseRoutes: Record<Locale, Record<string, string>>;

export declare function getLocalizedPath(canonicalPath: string, locale: Locale): string;
export declare function getCanonicalPath(localizedPath: string, locale: Locale): string;
`;
}
