import { promises as fs } from 'fs';
import { join, relative } from 'path';
import { parse } from '@babel/parser';
import type { Node, ObjectExpression } from '@babel/types';
import type { ExtractedRoute, ExtractRoutesOptions } from './types.js';
import { isRouteGroup } from './types.js';

/**
 * Extract routes from a TanStack Router project.
 *
 * Parses routeTree.gen.ts which is auto-generated by TanStack Router.
 * Uses TanStack's native route syntax ($param, {-$param}, etc.) without normalization.
 *
 * Throws an error if routeTree.gen.ts is not found - run `pnpm tsr generate` first.
 */
export async function extractTanStackRoutes(
  options: ExtractRoutesOptions,
): Promise<ExtractedRoute[]> {
  const { projectRoot } = options;

  const routeTreePath = await findRouteTree(projectRoot);
  if (!routeTreePath) {
    throw new Error(
      '[idiomi] Could not find routeTree.gen.ts in your TanStack Router project.\n' +
        'Run `pnpm tsr generate` or `npx @tanstack/router-cli generate` to generate it.',
    );
  }

  return extractFromRouteTree(routeTreePath, projectRoot);
}

/**
 * Find routeTree.gen.ts in common locations.
 */
async function findRouteTree(projectRoot: string): Promise<string | null> {
  const candidates = [
    join(projectRoot, 'src', 'routeTree.gen.ts'),
    join(projectRoot, 'app', 'routeTree.gen.ts'),
    join(projectRoot, 'routeTree.gen.ts'),
  ];

  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      return candidate;
    }
  }
  return null;
}

/**
 * Simple recursive AST walker.
 * Visits every node in the tree and calls the callback.
 */
function walk(node: Node, callback: (node: Node) => void): void {
  callback(node);
  for (const key in node) {
    const child = (node as unknown as Record<string, unknown>)[key];
    if (Array.isArray(child)) {
      for (const item of child) {
        if (item && typeof item === 'object' && 'type' in item) {
          walk(item as Node, callback);
        }
      }
    } else if (child && typeof child === 'object' && 'type' in child) {
      walk(child as Node, callback);
    }
  }
}

/**
 * Extract id and path string values from an ObjectExpression AST node.
 */
function extractIdAndPath(obj: ObjectExpression): {
  id?: string;
  path?: string;
} {
  let id: string | undefined;
  let path: string | undefined;

  for (const prop of obj.properties) {
    if (prop.type !== 'ObjectProperty') continue;
    if (prop.key.type !== 'Identifier') continue;

    const key = prop.key.name;
    if (key === 'id' || key === 'path') {
      if (prop.value.type === 'StringLiteral') {
        if (key === 'id') id = prop.value.value;
        if (key === 'path') path = prop.value.value;
      }
    }
  }

  return { id, path };
}

interface RouteInfo {
  variableName: string;
  path: string;
  parentVariableName?: string;
}

/**
 * Extract parent variable name from getParentRoute arrow function.
 * Pattern: getParentRoute: () => SomeRouteVariable
 */
function extractParentRoute(obj: ObjectExpression): string | undefined {
  for (const prop of obj.properties) {
    if (prop.type !== 'ObjectProperty') continue;
    if (prop.key.type !== 'Identifier') continue;
    if (prop.key.name !== 'getParentRoute') continue;

    // Arrow function: () => SomeRoute
    if (prop.value.type === 'ArrowFunctionExpression') {
      const body = prop.value.body;
      if (body.type === 'Identifier') {
        return body.name;
      }
    }
  }
  return undefined;
}

/**
 * Build full path by walking up the parent chain.
 */
function buildFullPath(
  routeInfo: RouteInfo,
  routeMap: Map<string, RouteInfo>,
): string[] {
  const segments: string[] = [];

  let current: RouteInfo | undefined = routeInfo;
  while (current) {
    // Add this route's segments (skip locale routes)
    if (!isLocaleRoute(current.path) && current.path !== '/') {
      const routeSegments = pathToSegments(current.path);
      segments.unshift(...routeSegments);
    }

    // Walk up to parent
    if (current.parentVariableName) {
      current = routeMap.get(current.parentVariableName);
    } else {
      break;
    }
  }

  return segments;
}

/**
 * Extract routes from TanStack Router's generated routeTree.gen.ts.
 *
 * Uses AST parsing to find .update({ id, path, getParentRoute }) definitions.
 * TanStack's route tree structure uses nested routes where child routes have
 * relative paths. We build full paths by walking up the parent chain.
 */
async function extractFromRouteTree(
  routeTreePath: string,
  projectRoot: string,
): Promise<ExtractedRoute[]> {
  const content = await fs.readFile(routeTreePath, 'utf-8');

  const ast = parse(content, {
    sourceType: 'module',
    plugins: ['typescript'],
  });

  // First pass: collect all route info with parent relationships
  const routeMap = new Map<string, RouteInfo>();

  walk(ast, (node) => {
    // Find variable declarations: const SomeRoute = SomeRouteImport.update({ ... })
    if (node.type !== 'VariableDeclaration') return;

    for (const declarator of node.declarations) {
      if (declarator.type !== 'VariableDeclarator') continue;
      if (declarator.id.type !== 'Identifier') continue;

      const init = declarator.init;
      if (!init || init.type !== 'CallExpression') continue;

      // Check if it's a .update() call
      if (init.callee.type !== 'MemberExpression') continue;
      if (init.callee.property.type !== 'Identifier') continue;
      if (init.callee.property.name !== 'update') continue;

      // The assigned variable name (e.g., Char123LocaleChar125BlogRoute)
      const variableName = declarator.id.name;

      // Get the first argument (should be an object expression)
      // Handle TypeScript `as any` casts by unwrapping TSAsExpression
      let arg = init.arguments[0];
      if (!arg) continue;

      // Unwrap TSAsExpression (e.g., `{ id: '...' } as any`)
      if (arg.type === 'TSAsExpression') {
        arg = arg.expression;
      }
      if (arg.type !== 'ObjectExpression') continue;

      // Extract id, path, and parent from the object
      const { path } = extractIdAndPath(arg);
      if (!path) continue;

      const parentVariableName = extractParentRoute(arg);

      routeMap.set(variableName, {
        variableName,
        path,
        parentVariableName,
      });
    }
  });

  // Second pass: build full paths from route hierarchy
  const routes: ExtractedRoute[] = [];

  for (const routeInfo of routeMap.values()) {
    // Skip routes that are just locale params (these are parent layout routes)
    if (isLocaleRoute(routeInfo.path)) {
      continue;
    }

    // Skip root route (just /)
    if (routeInfo.path === '/') {
      continue;
    }

    // Build full path by walking up parent chain
    const segments = buildFullPath(routeInfo, routeMap);

    // Filter out route groups (they don't appear in URLs)
    const filteredSegments = segments.filter((seg) => !isRouteGroup(seg));

    // Skip if no translatable segments remain
    if (filteredSegments.length === 0) {
      continue;
    }

    // Build the canonical path from filtered segments
    const canonicalPath = `/${filteredSegments.join('/')}`;

    routes.push({
      path: canonicalPath,
      source: relative(projectRoot, routeTreePath),
      type: 'page',
      segments: filteredSegments,
    });
  }

  return deduplicateRoutes(routes);
}

/**
 * Check if a route path is a locale parameter route.
 *
 * These are parent layout routes that handle locale switching, not content routes.
 * Only matches TanStack Router's special locale param syntax:
 * - /{-$locale} - optional locale param
 * - /{$locale} - required locale param
 *
 * Simple dynamic segments like /$slug are NOT locale routes - they're regular
 * dynamic route parameters in the URL.
 */
function isLocaleRoute(path: string): boolean {
  const normalized = path.trim();

  // /{-$...} - optional param with special chars (TanStack locale convention)
  if (/^\/\{-\$\w+\}$/.test(normalized)) {
    return true;
  }

  // /{$...} - required param with special chars (TanStack locale convention)
  if (/^\/\{\$\w+\}$/.test(normalized)) {
    return true;
  }

  // NOTE: We intentionally don't match /$param here because simple dynamic
  // segments like /$slug are regular route parameters, not locale routes.

  return false;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath);
    return stat.isFile();
  } catch {
    return false;
  }
}

function pathToSegments(path: string): string[] {
  return path.split('/').filter(Boolean);
}

function deduplicateRoutes(routes: ExtractedRoute[]): ExtractedRoute[] {
  const seen = new Set<string>();
  return routes.filter((route) => {
    if (seen.has(route.path)) {
      return false;
    }
    seen.add(route.path);
    return true;
  });
}
