import { promises as fs } from 'fs';
import { join, relative } from 'path';
import type { ExtractedRoute, ExtractRoutesOptions } from './types.js';
import { isRouteGroup } from './types.js';

/**
 * Extract routes from a TanStack Router project.
 *
 * Parses routeTree.gen.ts which is auto-generated by TanStack Router.
 * Uses TanStack's native route syntax ($param, {-$param}, etc.) without normalization.
 *
 * Throws an error if routeTree.gen.ts is not found - run `pnpm tsr generate` first.
 */
export async function extractTanStackRoutes(
  options: ExtractRoutesOptions,
): Promise<ExtractedRoute[]> {
  const { projectRoot } = options;

  const routeTreePath = await findRouteTree(projectRoot);
  if (!routeTreePath) {
    throw new Error(
      '[idiomi] Could not find routeTree.gen.ts in your TanStack Router project.\n' +
        'Run `pnpm tsr generate` or `npx @tanstack/router-cli generate` to generate it.',
    );
  }

  return extractFromRouteTree(routeTreePath, projectRoot);
}

/**
 * Find routeTree.gen.ts in common locations.
 */
async function findRouteTree(projectRoot: string): Promise<string | null> {
  const candidates = [
    join(projectRoot, 'src', 'routeTree.gen.ts'),
    join(projectRoot, 'app', 'routeTree.gen.ts'),
    join(projectRoot, 'routeTree.gen.ts'),
  ];

  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      return candidate;
    }
  }
  return null;
}

/**
 * Extract routes from TanStack Router's generated routeTree.gen.ts.
 *
 * Parses the .update({ id, path, getParentRoute }) definitions to extract routes.
 * TanStack's route tree structure already separates locale from content routes:
 * - Parent route has the locale param: { path: '/{-$locale}' }
 * - Child routes have clean paths: { path: '/about' }
 *
 * This means we don't need to strip locale prefixes - child route paths are already clean.
 */
async function extractFromRouteTree(
  routeTreePath: string,
  projectRoot: string,
): Promise<ExtractedRoute[]> {
  const content = await fs.readFile(routeTreePath, 'utf-8');

  // Match .update({ id: '...', path: '...' }) definitions
  // The path property contains just the segment for this route, not the full path
  const updateRegex =
    /\.update\(\{\s*id:\s*['"]([^'"]+)['"]\s*,\s*path:\s*['"]([^'"]+)['"]/g;

  const routes: ExtractedRoute[] = [];
  let match;

  while ((match = updateRegex.exec(content)) !== null) {
    const path = match[2];
    if (!path) continue;

    // Skip routes that are just locale params (these are parent layout routes)
    // Examples: /{-$locale}, /{$locale}, /$locale, /$lang
    if (isLocaleRoute(path)) {
      continue;
    }

    // Skip root route (just /)
    if (path === '/') {
      continue;
    }

    // Parse segments from the path
    const segments = pathToSegments(path);

    // Filter out route groups (they don't appear in URLs)
    const filteredSegments = segments.filter((seg) => !isRouteGroup(seg));

    // Skip if no translatable segments remain
    if (filteredSegments.length === 0) {
      continue;
    }

    // Build the canonical path from filtered segments
    const canonicalPath = `/${filteredSegments.join('/')}`;

    routes.push({
      path: canonicalPath,
      source: relative(projectRoot, routeTreePath),
      type: 'page',
      segments: filteredSegments,
    });
  }

  return deduplicateRoutes(routes);
}

/**
 * Check if a route path is a locale parameter route.
 *
 * These are parent layout routes that handle locale switching, not content routes.
 * Examples:
 * - /{-$locale} - optional locale param
 * - /{$locale} - required locale param
 * - /$locale - simple locale param
 * - /$lang - alternative naming
 */
function isLocaleRoute(path: string): boolean {
  // Match paths that are ONLY a locale param (not /about, /blog, etc.)
  // Pattern: starts with / followed by any param syntax
  const normalized = path.trim();

  // /{-$...} - optional param with special chars
  if (/^\/\{-\$\w+\}$/.test(normalized)) {
    return true;
  }

  // /{$...} - required param with special chars
  if (/^\/\{\$\w+\}$/.test(normalized)) {
    return true;
  }

  // /$... - simple param (only if it's just the param, nothing else)
  if (/^\/\$\w+$/.test(normalized)) {
    return true;
  }

  return false;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath);
    return stat.isFile();
  } catch {
    return false;
  }
}

function pathToSegments(path: string): string[] {
  return path.split('/').filter(Boolean);
}

function deduplicateRoutes(routes: ExtractedRoute[]): ExtractedRoute[] {
  const seen = new Set<string>();
  return routes.filter((route) => {
    if (seen.has(route.path)) {
      return false;
    }
    seen.add(route.path);
    return true;
  });
}
