import { promises as fs } from 'fs';
import { join } from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { extractTanStackRoutes } from './extract-tanstack.js';

// Test fixture paths
const fixtureRoot = join(__dirname, '__fixtures__', 'tanstack');

/**
 * Helper to generate a routeTree.gen.ts file content that matches TanStack Router's format.
 *
 * TanStack Router generates .update() calls for each route with id, path, and getParentRoute.
 * Child routes have clean paths (e.g., '/about') without locale prefix.
 * Parent routes contain the locale param (e.g., '/{-$locale}').
 */
function generateRouteTree(
  routes: Array<{ id: string; path: string; parent?: string }>,
): string {
  const imports = routes
    .map(
      (r) =>
        `import { Route as Route${sanitize(r.id)} } from './routes${r.id}'`,
    )
    .join('\n');

  const definitions = routes
    .map(
      (r) => `
const Route${sanitize(r.id)}Def = Route${sanitize(r.id)}.update({
  id: '${r.id}',
  path: '${r.path}',
  getParentRoute: () => ${r.parent ? `Route${sanitize(r.parent)}Def` : 'rootRoute'},
} as any)`,
    )
    .join('\n');

  return `
// Auto-generated by TanStack Router
${imports}

const rootRoute = {} as any;
${definitions}

export const routeTree = rootRoute;
`;
}

function sanitize(id: string): string {
  return id.replace(/[^a-zA-Z0-9]/g, '_');
}

describe('extractTanStackRoutes', () => {
  beforeEach(async () => {
    // Create fixture directories
    await fs.mkdir(join(fixtureRoot, 'src'), { recursive: true });
  });

  afterEach(async () => {
    // Clean up fixture directories
    await fs.rm(fixtureRoot, { recursive: true, force: true });
  });

  describe('routeTree.gen.ts parsing', () => {
    it('parses .update() route definitions', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/about', path: '/about' },
          { id: '/blog', path: '/blog' },
          { id: '/contact', path: '/contact' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/blog', segments: ['blog'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/contact', segments: ['contact'] }),
      );
    });

    it('skips locale parent routes with {-$locale} path', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/{-$locale}', path: '/{-$locale}' },
          { id: '/about', path: '/about', parent: '/{-$locale}' },
          { id: '/blog', path: '/blog', parent: '/{-$locale}' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Should NOT include the locale route itself
      expect(routes).not.toContainEqual(
        expect.objectContaining({ path: '/{-$locale}' }),
      );

      // Should include child routes with clean paths
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/blog', segments: ['blog'] }),
      );
    });

    it('skips locale parent routes with {$locale} path', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/{$locale}', path: '/{$locale}' },
          { id: '/about', path: '/about', parent: '/{$locale}' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).not.toContainEqual(
        expect.objectContaining({ path: '/{$locale}' }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('includes bare $param routes as regular dynamic segments', async () => {
      // Bare $param syntax is a regular dynamic segment, NOT a locale route.
      // Only {-$locale} and {$locale} (with braces) are treated as locale routes.
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/$category', path: '/$category' },
          { id: '/products', path: '/products', parent: '/$category' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Bare $param IS included - it's a regular dynamic segment
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/$category',
          segments: ['$category'],
        }),
      );
      // Child routes include parent segments
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/$category/products',
          segments: ['$category', 'products'],
        }),
      );
    });

    it('preserves dynamic segments with TanStack $param syntax', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/{-$locale}', path: '/{-$locale}' },
          { id: '/blog/$slug', path: '/blog/$slug', parent: '/{-$locale}' },
          {
            id: '/users/$userId/posts/$postId',
            path: '/users/$userId/posts/$postId',
            parent: '/{-$locale}',
          },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // TanStack syntax preserved (not normalized to [param])
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/blog/$slug',
          segments: ['blog', '$slug'],
        }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/users/$userId/posts/$postId',
          segments: ['users', '$userId', 'posts', '$postId'],
        }),
      );
    });

    it('skips root route (/)', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/{-$locale}', path: '/{-$locale}' },
          { id: '/', path: '/', parent: '/{-$locale}' },
          { id: '/about', path: '/about', parent: '/{-$locale}' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Root route is skipped (it has no translatable segments)
      expect(routes).not.toContainEqual(expect.objectContaining({ path: '/' }));
      // Other routes are included
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('handles empty route tree', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `// Empty route tree
const rootRoute = {} as any;
export const routeTree = rootRoute;
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toEqual([]);
    });

    it('deduplicates routes with same path', async () => {
      // Simulate duplicate definitions (shouldn't happen in practice)
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
const Route1 = {}.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => null,
} as any)

const Route2 = {}.update({
  id: '/about-duplicate',
  path: '/about',
  getParentRoute: () => null,
} as any)
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      const aboutRoutes = routes.filter((r) => r.path === '/about');
      expect(aboutRoutes).toHaveLength(1);
    });

    it('finds routeTree.gen.ts in app/ directory', async () => {
      await fs.mkdir(join(fixtureRoot, 'app'), { recursive: true });
      await fs.writeFile(
        join(fixtureRoot, 'app', 'routeTree.gen.ts'),
        generateRouteTree([{ id: '/about', path: '/about' }]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('finds routeTree.gen.ts at project root', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'routeTree.gen.ts'),
        generateRouteTree([{ id: '/about', path: '/about' }]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('filters out route groups', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        generateRouteTree([
          { id: '/(marketing)/pricing', path: '/(marketing)/pricing' },
          { id: '/(auth)/login', path: '/(auth)/login' },
        ]),
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Route groups filtered out, only the actual segment remains
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/pricing', segments: ['pricing'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/login', segments: ['login'] }),
      );
    });
  });

  describe('AST parsing edge cases', () => {
    it('handles multiline .update() calls with comments', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
// Auto-generated by TanStack Router
import { Route } from './routes/about'

const RouteAbout = Route.update({
  // Route identifier
  id: '/about',
  // Path segment for this route
  path: '/about',
  // Parent route reference
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = RouteAbout;
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('handles paths with special characters in strings', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
const RouteProducts = Route.update({
  id: '/products-and-services',
  path: '/products-and-services',
  getParentRoute: () => rootRoute,
} as any)

const RouteFAQ = Route.update({
  id: '/faq_page',
  path: '/faq_page',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = {};
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/products-and-services',
          segments: ['products-and-services'],
        }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/faq_page',
          segments: ['faq_page'],
        }),
      );
    });

    it('ignores routes with template literal paths', async () => {
      // Template literals should be ignored (only string literals are extracted)
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
const base = '/dynamic';
const RouteDynamic = Route.update({
  id: \`\${base}/test\`,
  path: \`\${base}/test\`,
  getParentRoute: () => rootRoute,
} as any)

const RouteStatic = Route.update({
  id: '/static',
  path: '/static',
  getParentRoute: () => rootRoute,
} as any)

export const routeTree = {};
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Only static route extracted, template literal ignored
      expect(routes).toHaveLength(1);
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/static', segments: ['static'] }),
      );
    });

    it('handles .update() without as any cast', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
const RouteAbout = Route.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
})

export const routeTree = RouteAbout;
`,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });
  });

  describe('error handling', () => {
    it('throws error when routeTree.gen.ts not found', async () => {
      // No routeTree.gen.ts exists - should throw
      await expect(
        extractTanStackRoutes({ projectRoot: fixtureRoot }),
      ).rejects.toThrow('Could not find routeTree.gen.ts');
    });

    it('provides helpful error message about generating the file', async () => {
      await expect(
        extractTanStackRoutes({ projectRoot: fixtureRoot }),
      ).rejects.toThrow('pnpm tsr generate');
    });
  });
});
