import { promises as fs } from 'fs';
import { join, relative } from 'path';
import type { ExtractedRoute, ExtractRoutesOptions } from './types.js';

/**
 * Extract routes from a TanStack Router project.
 *
 * Parses routeTree.gen.ts which is auto-generated by TanStack Router.
 * Throws an error if routeTree.gen.ts is not found - run `pnpm tsr generate` first.
 */
export async function extractTanStackRoutes(
  options: ExtractRoutesOptions,
): Promise<ExtractedRoute[]> {
  const { projectRoot } = options;

  const routeTreePath = await findRouteTree(projectRoot);
  if (!routeTreePath) {
    throw new Error(
      '[idiomi] Could not find routeTree.gen.ts in your TanStack Router project.\n' +
        'Run `pnpm tsr generate` or `npx @tanstack/router-cli generate` to generate it.',
    );
  }

  return extractFromRouteTree(routeTreePath, projectRoot);
}

/**
 * Find routeTree.gen.ts in common locations.
 */
async function findRouteTree(projectRoot: string): Promise<string | null> {
  const candidates = [
    join(projectRoot, 'src', 'routeTree.gen.ts'),
    join(projectRoot, 'app', 'routeTree.gen.ts'),
    join(projectRoot, 'routeTree.gen.ts'),
  ];

  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      return candidate;
    }
  }
  return null;
}

/**
 * Extract routes from TanStack Router's generated routeTree.gen.ts.
 *
 * Parses the FileRoutesByFullPath interface to get all route paths,
 * then strips locale prefixes and normalizes segments.
 */
async function extractFromRouteTree(
  routeTreePath: string,
  projectRoot: string,
): Promise<ExtractedRoute[]> {
  const content = await fs.readFile(routeTreePath, 'utf-8');

  // Match FileRoutesByFullPath interface
  // Use a more robust pattern that handles curly braces inside string literals
  // by matching from the opening brace to the closing brace at column 0
  const interfaceStart = content.indexOf(
    'export interface FileRoutesByFullPath',
  );
  if (interfaceStart === -1) return [];

  // Find the opening brace
  const openBrace = content.indexOf('{', interfaceStart);
  if (openBrace === -1) return [];

  // Find matching closing brace (simple balance counting)
  let braceCount = 1;
  let closeIdx = openBrace + 1;
  while (closeIdx < content.length && braceCount > 0) {
    // Skip string literals
    if (content[closeIdx] === "'" || content[closeIdx] === '"') {
      const quote = content[closeIdx];
      closeIdx++;
      while (closeIdx < content.length && content[closeIdx] !== quote) {
        if (content[closeIdx] === '\\') closeIdx++; // skip escaped chars
        closeIdx++;
      }
    } else if (content[closeIdx] === '{') {
      braceCount++;
    } else if (content[closeIdx] === '}') {
      braceCount--;
    }
    closeIdx++;
  }

  if (braceCount !== 0) return [];

  const interfaceBody = content.slice(openBrace + 1, closeIdx - 1);

  // Extract route paths from interface keys (e.g., '/{-$locale}/about': typeof ...)
  const routeRegex = /'([^']+)':/g;
  const routes: ExtractedRoute[] = [];
  let match;

  while ((match = routeRegex.exec(interfaceBody)) !== null) {
    const fullPath = match[1];
    if (!fullPath) continue;

    // Strip locale prefix and normalize
    const canonicalPath = stripLocalePrefix(fullPath);
    const segments = pathToSegments(canonicalPath);

    // Normalize $param to [param]
    const normalizedSegments = segments.map((seg) =>
      seg.startsWith('$') ? `[${seg.slice(1)}]` : seg,
    );

    const normalizedPath =
      normalizedSegments.length > 0 ? `/${normalizedSegments.join('/')}` : '/';

    routes.push({
      path: normalizedPath,
      source: relative(projectRoot, routeTreePath),
      type: 'page',
      segments: normalizedSegments,
    });
  }

  return deduplicateRoutes(routes);
}

/**
 * Strip locale prefix from TanStack route path.
 *
 * Handles:
 * - /{-$locale}/about → /about (optional locale)
 * - /{$locale}/about → /about (required locale)
 * - /$locale/about → /about (simple param)
 * - /$lang/about → /about (alternative naming)
 */
function stripLocalePrefix(path: string): string {
  // Remove optional locale: /{-$locale} or /{-$lang}
  let result = path.replace(/^\/\{-\$(?:locale|lang)\}/, '');

  // Remove required locale: /{$locale} or /{$lang}
  result = result.replace(/^\/\{\$(?:locale|lang)\}/, '');

  // Remove simple param: /$locale or /$lang
  result = result.replace(/^\/\$(?:locale|lang)(?=\/|$)/, '');

  // Handle trailing slash for root route
  if (result === '' || result === '/') {
    return '/';
  }

  // Remove trailing slash if present (e.g., /{-$locale}/ → /)
  if (result.endsWith('/') && result !== '/') {
    result = result.slice(0, -1);
  }

  return result || '/';
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath);
    return stat.isFile();
  } catch {
    return false;
  }
}

function pathToSegments(path: string): string[] {
  return path.split('/').filter(Boolean);
}

function deduplicateRoutes(routes: ExtractedRoute[]): ExtractedRoute[] {
  const seen = new Set<string>();
  return routes.filter((route) => {
    if (seen.has(route.path)) {
      return false;
    }
    seen.add(route.path);
    return true;
  });
}
