import { promises as fs } from 'fs';
import { join } from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { extractTanStackRoutes } from './extract-tanstack.js';

// Test fixture paths
const fixtureRoot = join(__dirname, '__fixtures__', 'tanstack');

describe('extractTanStackRoutes', () => {
  beforeEach(async () => {
    // Create fixture directories
    await fs.mkdir(join(fixtureRoot, 'src'), { recursive: true });
  });

  afterEach(async () => {
    // Clean up fixture directories
    await fs.rm(fixtureRoot, { recursive: true, force: true });
  });

  describe('routeTree.gen.ts parsing', () => {
    it('parses FileRoutesByFullPath interface', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/about': typeof AboutRoute
          '/blog': typeof BlogRoute
          '/contact': typeof ContactRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/blog', segments: ['blog'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/contact', segments: ['contact'] }),
      );
    });

    it('strips {-$locale} optional prefix from paths', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/{-$locale}': typeof LocaleRoute
          '/{-$locale}/about': typeof AboutRoute
          '/{-$locale}/blog': typeof BlogRoute
          '/{-$locale}/': typeof IndexRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/', segments: [] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/blog', segments: ['blog'] }),
      );
    });

    it('strips {$locale} required prefix from paths', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/{$locale}/about': typeof AboutRoute
          '/{$locale}/contact': typeof ContactRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/contact', segments: ['contact'] }),
      );
    });

    it('strips $locale prefix from paths', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/$locale/about': typeof AboutRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('preserves dynamic segments like $slug', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/{-$locale}/blog/$slug': typeof BlogPostRoute
          '/{-$locale}/users/$userId/posts/$postId': typeof UserPostRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/blog/[slug]',
          segments: ['blog', '[slug]'],
        }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({
          path: '/users/[userId]/posts/[postId]',
          segments: ['users', '[userId]', 'posts', '[postId]'],
        }),
      );
    });

    it('handles empty interface', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toEqual([]);
    });

    it('handles multi-line interface with comments', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        // Auto-generated by TanStack Router
        export interface FileRoutesByFullPath {
          // Home route
          '/{-$locale}/': typeof IndexRoute
          // About page
          '/{-$locale}/about': typeof AboutRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/', segments: [] }),
      );
      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('deduplicates routes from routeTree.gen.ts', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'src', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/{-$locale}': typeof LocaleRoute
          '/{-$locale}/': typeof IndexRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      // Both paths resolve to '/' - should be deduplicated
      const rootRoutes = routes.filter((r) => r.path === '/');
      expect(rootRoutes).toHaveLength(1);
    });

    it('finds routeTree.gen.ts in app/ directory', async () => {
      // Some projects use app/ instead of src/
      await fs.mkdir(join(fixtureRoot, 'app'), { recursive: true });
      await fs.writeFile(
        join(fixtureRoot, 'app', 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/about': typeof AboutRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });

    it('finds routeTree.gen.ts at project root', async () => {
      await fs.writeFile(
        join(fixtureRoot, 'routeTree.gen.ts'),
        `
        export interface FileRoutesByFullPath {
          '/about': typeof AboutRoute
        }
        `,
      );

      const routes = await extractTanStackRoutes({ projectRoot: fixtureRoot });

      expect(routes).toContainEqual(
        expect.objectContaining({ path: '/about', segments: ['about'] }),
      );
    });
  });

  describe('error handling', () => {
    it('throws error when routeTree.gen.ts not found', async () => {
      // No routeTree.gen.ts exists - should throw
      await expect(
        extractTanStackRoutes({ projectRoot: fixtureRoot }),
      ).rejects.toThrow('Could not find routeTree.gen.ts');
    });

    it('provides helpful error message about generating the file', async () => {
      await expect(
        extractTanStackRoutes({ projectRoot: fixtureRoot }),
      ).rejects.toThrow('pnpm tsr generate');
    });
  });
});
