// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTrans,
  createUseLocale,
  createUseT,
  plural,
} from '@idioma/react';
import { translations } from './.generated/translations';
import type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
} from './.generated/types';

export const Trans = createTrans<TranslationKey, MessageValues, MessageComponents>(translations);
export const useT = createUseT<StringOnlyKey, MessageValues>(translations);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export { plural };
export type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
};
