// Auto-generated by @idioma/core
import { _createTFactory } from '@idioma/core/runtime';
import type { Locale, TranslationKey, MessageValues } from './.generated/types';

export const createT = (locale: Locale) =>
  _createTFactory<TranslationKey, MessageValues>(locale);

export type { Locale, TranslationKey, MessageValues };
