// Auto-generated by @idiomi/core
// Do not edit directly
// Server-only exports for TanStack Start

import { createRequestHandler } from '@idiomi/tanstack-react/server';
import {
  defaultLocale,
  detection,
  locales,
  prefixStrategy,
} from './.generated/config';
import type { Locale } from './.generated/types';

export const handleLocale = createRequestHandler<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  detection,
});
