// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idioma/react/runtime-suspense';
import type { IdiomaTypes, Locale } from './.generated/types';

const config = {
  locales: ["en","es","ar"] as const,
};

export const Trans = createTransSuspense<IdiomaTypes>(config);
export const useT = createUseTSuspense<IdiomaTypes>(config);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type { IdiomaTypes, Locale };
