// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idioma/react/runtime-suspense';
import type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
} from './.generated/types';

const config = {
  locales: ["en","es","ar"] as const,
};

export const Trans = createTrans<TranslationKey, MessageValues, MessageComponents>(config);
export const useT = createUseT<StringOnlyKey, MessageValues>(config);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type {
  Locale,
  MessageComponents,
  MessageValues,
  StringOnlyKey,
  TranslationKey,
};
