// Auto-generated by @idioma/core
// Do not edit directly

import {
  createIdiomaProvider,
  createTransSuspense,
  createUseLocale,
  createUseTSuspense,
} from '@idioma/react/runtime-suspense';
import type { IdiomaConfig, Locale } from './.generated/types';

const config = {
  locales: ["en","es","ar"] as const,
};

export const Trans = createTransSuspense<IdiomaConfig>(config);
export const useT = createUseTSuspense<IdiomaConfig>(config);
export const IdiomaProvider = createIdiomaProvider();
export const useLocale = createUseLocale();

export type { IdiomaConfig, Locale };
