// Auto-generated by @idioma/core
// Do not edit directly
// Plain JavaScript translation utilities (no React dependency)

import type { StringOnlyKey, MessageValues } from './.generated/types';

// Re-export createT from runtime.
// In production, Babel inlines translations at each call site.
// For dynamic strings, Babel injects the translations import automatically.
export { createT } from '@idioma/core/runtime';

export type { StringOnlyKey, MessageValues };
