// Auto-generated by @idiomi/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomiProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idiomi/react';
import {
  createLocaleHead,
  createLocaleLoader,
  createUrlHandler,
} from '@idiomi/tanstack-react';
import {
  defaultLocale,
  detection,
  localeParamName,
  locales,
  metadataBase,
  prefixStrategy,
} from './.generated/config';
import type { IdiomiTypes, Locale } from './.generated/types';

export { locales, defaultLocale } from './.generated/config';

export const LocaleHead = createLocaleHead({
  metadataBase,
  locales,
  defaultLocale,
  prefixStrategy,
});

export const { localeLoader, detectLocale } = createLocaleLoader<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
  detection,
  localeParamName,
});

export const { localizeUrl } = createUrlHandler<Locale>({
  locales,
  defaultLocale,
  prefixStrategy,
});

export { localeParamName };

export { getLocaleHead } from '@idiomi/react';

export const Trans = createTrans<IdiomiTypes>();

export const useT = createUseT<IdiomiTypes>();

export const IdiomiProvider = createIdiomiProvider();

export const useLocale = createUseLocale<Locale>();

export type { IdiomiTypes, Locale };
