// Auto-generated by @idiomi/core
// Do not edit directly
// Translations are inlined by Babel at build time

import {
  createIdiomiProvider,
  createTrans,
  createUseLocale,
  createUseT,
} from '@idiomi/react';
import type { IdiomiTypes, Locale } from './.generated/types';
import { createLink, createLocaleHead } from '@idiomi/tanstack-react';
import { locales, defaultLocale, prefixStrategy, detection } from './.generated/config';
import { redirect } from '@tanstack/react-router';

export const Link = createLink({
  defaultLocale,
  prefixStrategy,
});
export const LocaleHead = createLocaleHead({
  metadataBase: "http://localhost:5178",
  locales: ["en","es"],
  defaultLocale: "en",
  prefixStrategy: "as-needed",
});

/**
 * TanStack Router beforeLoad function for locale detection.
 * Handles URL prefix strategy and redirects.
 */
export function localeLoader({
  location,
}: {
  location: { pathname: string; search: string; hash: string };
}) {
  const pathLocale = extractLocaleFromPath(location.pathname);

  // Strategy: 'never' - no URL prefixes, just detect
  if (prefixStrategy === 'never') {
    return { locale: pathLocale ?? detectClientLocale() };
  }

  // No locale in path - check if we need to redirect
  if (!pathLocale) {
    const detected = detectClientLocale();

    // Redirect if: always prefix OR detected is non-default
    if (prefixStrategy === 'always' || detected !== defaultLocale) {
      throw redirect({
        to: `/${detected}${location.pathname}${location.search}${location.hash}`,
      });
    }

    return { locale: detected };
  }

  // Locale in path - use it
  return { locale: pathLocale };
}

/** Low-level detection (exported for manual use cases) */
export function detectClientLocale(): string {
  for (const source of detection.order) {
    if (source === 'cookie') {
      const cookie = getCookie(detection.cookieName);
      if (cookie && locales.includes(cookie)) return cookie;
    }
    if (source === 'header') {
      // 'header' = navigator.languages on client (skip during SSR)
      if (typeof navigator !== 'undefined' && navigator.languages?.length) {
        const matched = matchBrowserLocale(navigator.languages);
        if (matched) return matched;
      }
    }
  }
  return defaultLocale;
}

/** Simple browser-compatible locale matching (no Node.js deps) */
function matchBrowserLocale(browserLocales: readonly string[]): string | undefined {
  for (const browserLang of browserLocales) {
    const normalized = browserLang.toLowerCase();
    // Exact match
    for (const locale of locales) {
      if (locale.toLowerCase() === normalized) return locale;
    }
    // Prefix match (e.g., 'en-US' matches 'en')
    const prefix = normalized.split('-')[0];
    for (const locale of locales) {
      if (locale.toLowerCase() === prefix) return locale;
      if (locale.toLowerCase().startsWith(prefix + '-')) return locale;
    }
  }
  return undefined;
}

function extractLocaleFromPath(pathname: string): string | undefined {
  const segment = pathname.split('/')[1];
  if (segment && (locales as readonly string[]).includes(segment)) {
    return segment;
  }
  return undefined;
}

function getCookie(name: string): string | undefined {
  if (typeof document === 'undefined') return undefined;
  const match = document.cookie.match(new RegExp(`(?:^|;\\s*)${name}=([^;]*)`));
  return match?.[1];
}
export { getLocaleHead } from '@idiomi/react';

export const Trans = createTrans<IdiomiTypes>();
export const useT = createUseT<IdiomiTypes>();
export const IdiomiProvider = createIdiomiProvider();
export const useLocale = createUseLocale();

export type { IdiomiTypes, Locale };
